import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import BasicTemplate from '@/components/Templates/BasicTemplate'

export default function Network() {


  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <main className={styles.main}>
          <h1>ネットワーク図</h1>
        </main>
      </BasicTemplate>
    </>
  )
}
