import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import BasicTemplate from '@/components/Templates/BasicTemplate'

const inter = Inter({ subsets: ['latin'] })

export default function Skills() {

  const skills = ['HTML', 'CSS', 'JavaScript', 'React.js', 'Next.js'];

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <main className={styles.main}>
          <h1>My Skills</h1>
          <ul>
            {skills.map((skill) => (
              <div key={skill}>
                <li>{skill}</li>
              </div>
            ))}
          </ul>
        </main>
      </BasicTemplate>
    </>
  )
}
