import { useState } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import BasicTemplate from '@/components/Templates/BasicTemplate'
import Animation from '@/components/Animation'

const inter = Inter({ subsets: ['latin'] })

export default function Todo() {

  const [todo, setTodo] = useState<string[]>([
    '論文を読む',
    '新しいシステムの仕様を考える',
    '簿記の試験勉強を頑張る'
  ]);
  const [inputItem, setInputItem] = useState<string>("");
  const [visible, setVisible] = useState(false);

  const finishedItem = (item: string) => {
    const newTodo = todo.filter((todo) => todo !== item);
    setTodo(newTodo);
    if(newTodo.length === 0) {
      setVisible(true);
    };
  };
  const insertItem = () => {
    // validation
    if(inputItem === "") return;

    const newTodo = todo.concat(inputItem);
    setTodo(newTodo);
    setInputItem("");
    setVisible(false);
  };

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <main className={styles.main}>
          <h1>ToDo リスト</h1>
          <div>
            <input type="text" placeholder="ToDoを追加" onChange={(e) => setInputItem(e.target.value)} value={inputItem}/>
            <button onClick={()=>insertItem()}>追加</button>
          </div>
          <table>
            <thead>
              <tr>
                <th>TODO</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              {todo.map((item, index) => {
                return (
                  <tr key={index}>
                    <td>{item}</td>
                    <td><button onClick={() => finishedItem(item)}>完了</button></td>
                  </tr>
                );
              })}
            </tbody>
          </table>
          {visible === true ? <Animation /> : null}
        </main>
      </BasicTemplate>
      
    </>
  )
}
