import { useState } from 'react'
import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Header from '@/components/Header'
import BasicTemplate from '@/components/Templates/BasicTemplate'
import Animation from '@/components/Animation'
import  TodoList  from '../components/Todo.json'

const inter = Inter({ subsets: ['latin'] })

export default function Todo() {

  const [todo, setTodo] = useState(TodoList)
  const [inputItem, setInputItem] = useState<string>("");
  const [visible, setVisible] = useState(false);

  const finishedItem = (id: number) => {
    const newTodo = todo.parentTodo;
    console.log(newTodo);
    // setTodo(newTodo);
    if(newTodo.length === 0) {
      setVisible(true);
    };
  };
  const insertItem = () => {
    // validation
    if(inputItem === "") return;

    let newTodo = todo;
    newTodo.parentTodo.push({ id:newTodo.parentTodo.length+1 ,text: inputItem});
    setTodo(newTodo);
    console.log(newTodo);
    setInputItem("");
    setVisible(false);
  };

  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <main className={styles.main}>
          <h1>ToDo リスト</h1>
          <div>
            <input type="text" placeholder="ToDoを追加" onChange={(e) => setInputItem(e.target.value)} value={inputItem}/>
            <button onClick={()=>insertItem()}>追加</button>
          </div>

          <table>
            <thead>
                <tr>
                  <th>TODO</th>
                  <th>Status</th>
                </tr>
              </thead>
            <tbody>
              {todo.parentTodo.map((item, index) => (
                  <tr key={index}>
                      <td>{item.text}</td>
                      <td><button onClick={() => finishedItem(item.id)}>完了</button></td>
                  </tr>
              ))}
            </tbody>
          </table>
          {visible === true ? <Animation /> : null}
        </main>
      </BasicTemplate>
      
    </>
  )
}
